title: Andreas Mausch Gallery
email: andreas.mausch@gmail.com
description: ""
baseurl: ""
url: "https://gallery.andreas-mausch.de"

markdown: kramdown
permalink: pretty

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - generate-thumbnails.sh
  - README.md
  - vendor/
